export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const GET_TEACHERS = "GET_TEACHERS";
export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_TEACHER = "GET_TEACHER";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";