export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const GET_STUDENTS = "GET_STUDENTS";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENT = "GET_STUDENT";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";